language: go
sudo: required
dist: trusty
branches:
  only:
    - /^v.*_kel\.\d+$/
go:
  - 1.5
before_install:
  - openssl aes-256-cbc -K $encrypted_3101bddd07d7_key -iv $encrypted_3101bddd07d7_iv -in gcp-travisci.json.enc -out gcp-travisci.json -d
  - echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update -qq && sudo apt-get install google-cloud-sdk
  - gcloud auth activate-service-account --key-file gcp-travisci.json
install:
  - gcloud config set project project-kel
before_script:
  - ./scripts/ci/deps.sh
script:
  - ./scripts/ci/build.sh
after_success:
  - ./scripts/ci/deploy.sh
