apiVersion: v1
kind: Pod
metadata:
  name: k8s-master
spec:
  hostNetwork: true
  containers:
    - name: controller-manager
      image: quay.io/kelproject/hyperkube:VERSION
      command:
        - /hyperkube
        - controller-manager
        - --master=127.0.0.1:8080
        - --v=2
    - name: apiserver
      image: quay.io/kelproject/hyperkube:VERSION
      command:
        - /hyperkube
        - apiserver
        - --allow-privileged=true
        - --service-cluster-ip-range=10.3.0.1/24
        - --address=127.0.0.1
        - --etcd-servers=http://127.0.0.1:4001
        - --cluster-name=kubernetes
        - --v=2
    - name: scheduler
      image: quay.io/kelproject/hyperkube:VERSION
      command:
        - /hyperkube
        - scheduler
        - --master=127.0.0.1:8080
        - --v=2
